### PR TITLE
mandate black

### PR DESCRIPTION
**Pull request by stuartleigh**

### CODE REVIEW

**Review by Darth-Knoppix — APPROVED** [review]
🙏

**Review by bart613 — APPROVED** [review]
👍 

I'm waiting the day when we use `black` as part of CI pipeline :)

**Review by rodalmeida — APPROVED** [review]

**Comment by bal-jhand** [comment]
👍

**Review by andrewswait — APPROVED** [review]
Yes please 👌

**Comment by wizardels** [comment]
😍

**Pull request merged**
